name: maisound
description: A sound app for the world to enjoy music and sound effects. Oh yeah, and it's free! And open source!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  fl_chart: any
  audioplayers: ^5.2.1
  file_picker: ^7.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutterflow_ui: ^0.2.0+1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.15
  mongo_dart: ^0.9.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
      - assets/instruments/piano/

  uses-material-design: true

